<a href="https://colab.research.google.com/github/Ayushriba/project/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# 5 different 3D NumPy arrays
arrays = [
    np.array([[[2, 5], [8, 11]],
              [[14, 17], [20, 23]]]),

    np.array([[[31, 34, 37],
               [40, 43, 46]]]),

    np.array([[[52], [55], [58]],
              [[61], [64], [67]],
              [[70], [73], [76]]]),

    np.array([[[81, 84],
               [87, 90],
               [93, 96]],
              [[99, 102],
               [105, 108],
               [111, 114]]]),

    np.array([[[121, 124],
               [127, 130]],
              [[133, 136],
               [139, 142]],
              [[145, 148],
               [151, 154]]])
]

# Display information for each array
for n, arr in enumerate(arrays, start=1):
    print(f"\n========== Array {n} ==========")

    # Display complete array
    print("Complete Array:")
    print(arr)

    # Number of dimensions
    print("Number of dimensions (ndim):", arr.ndim)

    # Access and print every element using indexing
    print("Elements:")
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            for k in range(arr.shape[2]):
                print(f"arr[{i}][{j}][{k}] = {arr[i][j][k]}")


========== Array 1 ==========
Complete Array:
[[[ 2  5]
  [ 8 11]]

 [[14 17]
  [20 23]]]
Number of dimensions (ndim): 3
Elements:
arr[0][0][0] = 2
arr[0][0][1] = 5
arr[0][1][0] = 8
arr[0][1][1] = 11
arr[1][0][0] = 14
arr[1][0][1] = 17
arr[1][1][0] = 20
arr[1][1][1] = 23

========== Array 2 ==========
Complete Array:
[[[31 34 37]
  [40 43 46]]]
Number of dimensions (ndim): 3
Elements:
arr[0][0][0] = 31
arr[0][0][1] = 34
arr[0][0][2] = 37
arr[0][1][0] = 40
arr[0][1][1] = 43
arr[0][1][2] = 46

========== Array 3 ==========
Complete Array:
[[[52]
  [55]
  [58]]

 [[61]
  [64]
  [67]]

 [[70]
  [73]
  [76]]]
Number of dimensions (ndim): 3
Elements:
arr[0][0][0] = 52
arr[0][1][0] = 55
arr[0][2][0] = 58
arr[1][0][0] = 61
arr[1][1][0] = 64
arr[1][2][0] = 67
arr[2][0][0] = 70
arr[2][1][0] = 73
arr[2][2][0] = 76

========== Array 4 ==========
Complete Array:
[[[ 81  84]
  [ 87  90]
  [ 93  96]]

 [[ 99 102]
  [105 108]
  [111 114]]]
Number of dimensions (ndim): 3
Elements:
arr[0][0][0] = 81
ar